name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u DOCKER_USER -p DOCKER_PASSWORD
      - name: docker build
        run: |
          docker build ./somme -t ${{ secrets.DOCKERHUB_USERNAME }}/somme:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./somme/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/somme:latest
      - name: pull image
        run: docker run -d -p 80:80 --name somme ${{ secrets.DOCKERHUB_USERNAME }}/somme:latest
      - name: create and run container
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/somme:latest
          run: docker ps -a
